# Generated by Django 3.1.3 on 2020-11-18 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EngineSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_run', models.BooleanField(default=True)),
                ('max_tasks', models.SmallIntegerField()),
                ('hubs_main_url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('last_poll_date_time', models.DateTimeField(auto_created=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('poll', models.BooleanField(default=False)),
                ('poll_interval', models.SmallIntegerField(default=0, null=True)),
            ],
            options={
                'ordering': ['name', 'last_poll_date_time'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('date_time', models.DateTimeField(auto_created=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('author_link', models.URLField()),
                ('author_name', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('body', models.TextField()),
                ('hash', models.CharField(max_length=300)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.hub')),
            ],
            options={
                'ordering': ['date_time', 'title'],
            },
        ),
    ]
